apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: $($vars.name)
  namespace: $($vars.namespace)
spec:
  secretName: $($vars.name)
  dnsNames:
  - $($vars.domain)
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - $($vars.domain)
  issuerRef:
    name: $($vars.type)
    namespace: $($vars.issuerNamespace)
    kind: ClusterIssuer