apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - $($vars.domain)
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - $($vars.domain)
  issuerRef:
    name: $($vars.type)
    kind: ClusterIssuer