apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: $($vars.type)
spec:
  acme:
    server: $($vars.server)
    email: $($config.adminEmail)
    privateKeySecretRef:
      name: $($vars.type)
    http01: {}