apiVersion: v1
kind: PersistentVolume
metadata:
  name: $($vars.name)
spec:
  capacity:
    storage: $($vars.sizeGB)Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: $($vars.storageAccountName)-storage-secret
    shareName: $($vars.shareName)
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=1000
  - gid=1000

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: $($vars.name)-claim
spec:
  accessModes:
    - ReadWriteMany
  mountOptions:
  resources:
    requests:
      storage: $($vars.sizeGB)Gi
  storageClassName: ""
  volumeName: $($vars.name)